In [1]:
import pandas as pd
from pathlib import Path

In [2]:
folder_path = Path("data/excel_data")

# Read and combine all .xlsx files
files = list(folder_path.glob("*.xlsx"))

df = pd.concat([pd.read_excel(f) for f in files], ignore_index=True)

/Users/abbymihaly/.venvs/lede/lib/python3.13/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/Users/abbymihaly/.venvs/lede/lib/python3.13/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/Users/abbymihaly/.venvs/lede/lib/python3.13/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/Users/abbymihaly/.venvs/lede/lib/python3.13/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/Users/abbymihaly/.venvs/lede/lib/python3.13/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/Users/abbymihaly/.venvs/lede/lib/python3.13/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/Users/abbymihaly/.venvs/lede/lib/python3.13/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [3]:
df.head()

,RecordNumber,FileNo,BusinessType,BusinessName,NaicsCodes,PrincipalOfficeAddress1,PrincipalOfficeAddress2,PrincipalOfficeCity,PrincipalOfficeState,PrincipalOfficeZipCode,...,AgentZipCode,DateOfIncorporation,BusinessStatus,LastAnnualReportDate,TerminationDate,FiscalYearMonth,TermDate,DissolvedDate,SubType,ExpirationDate
0,22341,L0023033,Domestic Business Corporation,"VERMONT WOOD PELLET COMPANY, INC.",321999-All Other Miscellaneous Wood Product Ma...,1105 RTE 7B Central,NaN,NORTH CLARENDON,VT,05759,...,05759,2008-04-14,Active - In Good Standing,2025-12-31,NaN,12.0,0001-01-01,NaN,NaN,NaN
1,40981,V00046,Domestic Business Corporation,NEWPORT AND RICHFORD RAILROAD COMPANY,NaN,84 PINE ST,NaN,BURLINGTON,VT,05402,...,05402,1880-12-06,Inactive - Administratively Terminated,2001-12-31,NaN,12.0,NaN,NaN,NaN,NaN
2,40988,V00052,Domestic Business Corporation,CLARENDON AND PITTSFORD RAILROAD COMPANY,NaN,ONE RAILWAY LN.,NaN,BURLINGTON,VT,05401,...,05401,1885-09-09,Active - In Good Standing,2025-12-31,NaN,12.0,NaN,NaN,NaN,NaN
3,41052,V00116,Domestic Business Corporation,RUTLAND FIRE CLAY CO.,NaN,8 Madison Ave,NaN,Rutland,VT,05701,...,05464,1883-12-12,Active - In Good Standing,2025-12-31,NaN,12.0,NaN,NaN,NaN,NaN
4,41062,V00124,Domestic Business Corporation,"PGL AND SONS HOLDINGS, INC.",NaN,1118 RT 14,NaN,HARTFORD,VT,05047,...,05001,1881-04-21,Inactive - Administratively Terminated,2012-12-31,2014-06-01,12.0,NaN,NaN,NaN,NaN

### Making new df with only General Stores.

Defining general stors as those stores that include in their titles:
1) "General Store"
2) "Country Store"
or 
3) "Store" + name of a Vermont city or town

In [4]:
# first, list all vermont towns

df_towns = pd.read_csv('Vermont Town Data/FS_VCGI_OPENDATA_Boundary_BNDHASH_poly_towns_SP_v1_-8833757079210321760.csv')

df_towns.head()

,OBJECTID,FIPS6,TOWNNAME,TOWNNAMEMC,CNTY,TOWNGEOID,Shape__Area,Shape__Length
0,1,9030.0,CANAAN,Canaan,9,5000911800,8.613393e+07,63085.366335
1,2,11040.0,FRANKLIN,Franklin,11,5001127100,1.058529e+08,42591.256754
2,3,11015.0,BERKSHIRE,Berkshire,11,5001105425,1.085458e+08,42302.494352
3,4,11050.0,HIGHGATE,Highgate,11,5001133025,1.555736e+08,57367.840529
4,5,11060.0,RICHFORD,Richford,11,5001159125,1.118973e+08,42398.623987

Now make a new df_general_stores with those three filters General Store, Country Store and town + Store

In [5]:
# Title case all the towns
df_towns['TOWNNAME'] = df_towns['TOWNNAME'].str.title()

# Make a list of towns
town_list = df_towns["TOWNNAME"].tolist()

town_list

['Canaan',
 'Franklin',
 'Berkshire',
 'Highgate',
 'Richford',
 'Alburgh',
 'Norton',
 'Averill',
 'Holland',
 'Jay',
 'Troy',
 'Lemington',
 'Isle La Motte',
 "Avery'S Gore",
 "Warren'S Gore",
 "Warner'S Grant",
 'Sheldon',
 'Morgan',
 'Lewis',
 'Swanton',
 'North Hero',
 'Enosburgh',
 'Westfield',
 'Charleston',
 'Saint Albans Town',
 'Brownington',
 'Fairfield',
 'Bloomfield',
 'Brighton',
 'Irasburg',
 'Lowell',
 'Bakersfield',
 'Saint Albans City',
 'Westmore',
 'Ferdinand',
 'Brunswick',
 'Belvidere',
 'Georgia',
 'Albany',
 'Grand Isle',
 'Waterville',
 'Fairfax',
 'Newark',
 'Fletcher',
 'Barton',
 'Sutton',
 'Glover',
 'Milton',
 'East Haven',
 'Craftsbury',
 'Cambridge',
 'Sheffield',
 'South Hero',
 'Granby',
 'Greensboro',
 'Burke',
 'Westford',
 'Johnson',
 'Wolcott',
 'Underhill',
 'Wheelock',
 'Guildhall',
 'Victory',
 'Hyde Park',
 'Morristown',
 'Hardwick',
 'Stannard',
 'Kirby',
 'Stowe',
 'Elmore',
 'Lyndon',
 'Walden',
 'Lunenburg',
 'Jericho',
 'Saint Johnsbury',
 'Concord',
 'Woodbury',
 'Worcester',
 'Bolton',
 'Waterford',
 'Calais',
 'Saint George',
 'Barnet',
 'Middlesex',
 'Peacham',
 'Duxbury',
 'Charlotte',
 'Huntington',
 'Waterbury',
 'Marshfield',
 'East Montpelier',
 'Moretown',
 'Montpelier',
 'Starksboro',
 'Groton',
 'Plainfield',
 'Monkton',
 'Fayston',
 'Berlin',
 'Ferrisburgh',
 'Barre Town',
 'Buels Gore',
 'Orange',
 'Barre City',
 'Bristol',
 'Topsham',
 'Vergennes',
 'New Haven',
 'Panton',
 'Waltham',
 'Lincoln',
 'Washington',
 'Addison',
 'Corinth',
 'Weybridge',
 'Chelsea',
 'Middlebury',
 'Ripton',
 'Bridport',
 'Cornwall',
 'Vershire',
 'West Fairlee',
 'Fairlee',
 'Hancock',
 'Tunbridge',
 'Salisbury',
 'Rochester',
 'Shoreham',
 'Strafford',
 'Bethel',
 'Thetford',
 'Royalton',
 'Orwell',
 'Pittsfield',
 'Sharon',
 'Stockbridge',
 'Norwich',
 'Barnard',
 'Benson',
 'Hartford',
 'Killington',
 'Bridgewater',
 'West Haven',
 'Fair Haven',
 'Hartland',
 'Plymouth',
 'Shrewsbury',
 'Reading',
 'Windsor',
 'Wallingford',
 'Mount Holly',
 'Pawlet',
 'Danby',
 'Mount Tabor',
 'Weston',
 'Andover',
 'Springfield',
 'Rupert',
 'Dorset',
 'Peru',
 'Landgrove',
 'Londonderry',
 'Grafton',
 'Windham',
 'Sandgate',
 'Winhall',
 'Manchester',
 'Jamaica',
 'Townshend',
 'Westminster',
 'Arlington',
 'Sunderland',
 'Stratton',
 'Brookline',
 'Wardsboro',
 'Shaftsbury',
 'Glastenbury',
 'Somerset',
 'Putney',
 'Newfane',
 'Dover',
 'Dummerston',
 'Bennington',
 'Woodford',
 'Searsburg',
 'Wilmington',
 'Marlboro',
 'Brattleboro',
 'Readsboro',
 'Pownal',
 'Stamford',
 'Whitingham',
 'Halifax',
 'Guilford',
 'Vernon',
 'Montgomery',
 'Eden',
 'Maidstone',
 'Colchester',
 'Danville',
 'Winooski',
 'Cabot',
 'Shelburne',
 'Richmond',
 'Hinesburg',
 'Pomfret',
 'Woodstock',
 'Rutland City',
 'Burlington',
 'Braintree',
 'Randolph',
 'Essex',
 'Ryegate',
 'Newbury',
 'South Burlington',
 'Williston',
 'Williamstown',
 'Brookfield',
 'Bradford',
 'Poultney',
 'Tinmouth',
 'Wells',
 'Middletown Springs',
 'West Windsor',
 'Chester',
 'Cavendish',
 'Baltimore',
 'Weathersfield',
 'Newport Town',
 'Derby',
 'Coventry',
 'Newport City',
 'Northfield',
 'Waitsfield',
 'Rockingham',
 'Athens',
 'Granville',
 'Roxbury',
 'Warren',
 'Goshen',
 'Whiting',
 'Leicester',
 'Chittenden',
 'Sudbury',
 'Hubbardton',
 'Castleton',
 'Ira',
 'Brandon',
 'Pittsford',
 'West Rutland',
 'Proctor',
 'Rutland Town',
 'Mendon',
 'Clarendon',
 'Ludlow',
 'Essex Junction']

In [6]:
# for "GENERAL STORE" and "COUNTRY STORE" / add word boundaries to the standalone phrases 
phrase_mask = df["BusinessName"].str.contains(
    r"\bGeneral Store\b|\bCountry Store\b",
    case=False,
    na=False,
)

# for town + "store"
# create a pattern for each town: must contain both 'Store' and the town name.
# Enforce standalone word boundaries (\b) around the word 'store'
town_pattern = "|".join(fr"(?=.*\bstore\b)(?=.*{town})" for town in town_list)

town_mask = df["BusinessName"].str.contains(
    town_pattern,
    case=False,
    na=False,
)

# filter df
df_general_stores = df[phrase_mask | town_mask]

In [7]:
df_general_stores.head(40)

,RecordNumber,FileNo,BusinessType,BusinessName,NaicsCodes,PrincipalOfficeAddress1,PrincipalOfficeAddress2,PrincipalOfficeCity,PrincipalOfficeState,PrincipalOfficeZipCode,...,AgentZipCode,DateOfIncorporation,BusinessStatus,LastAnnualReportDate,TerminationDate,FiscalYearMonth,TermDate,DissolvedDate,SubType,ExpirationDate
753,55376,V10041,Domestic Business Corporation,"OLD BENNINGTON COUNTRY STORE, INC.",NaN,39 WEST ROAD,NaN,BENNINGTON,VT,05201,...,05201,1960-06-17,Dissolved,1985-12-31,NaN,12.0,NaN,1987-03-20,NaN,NaN
799,55857,V10258,Domestic Business Corporation,"THE VERMONT COUNTRY STORE, INC.",454110-Electronic Shopping and Mail-Order Houses,5650 Main Street,NaN,Manchester Center,VT,05255,...,05255,1961-01-09,Active - In Good Standing,2026-04-30,NaN,4.0,0001-01-01,NaN,NaN,NaN
913,57273,V10910,Domestic Business Corporation,"COUNTRY STORE RESTAURANT, INC.",NaN,NaN,NaN,MANCHESTER,VT,05254,...,05061,1962-08-02,Inactive - Administratively Terminated,1987-07-31,NaN,7.0,NaN,NaN,NaN,NaN
1053,58742,V11578,Domestic Business Corporation,"GRAFTON VILLAGE STORE, INC.",NaN,5 BROWN STREET,NaN,BELLOWS FALLS,VT,05101,...,05101,1963-12-16,Dissolved,2009-12-31,NaN,12.0,NaN,2010-03-10,NaN,NaN
1136,59684,V12009,Domestic Business Corporation,"CHARLESTOWN MILL STORE OF BENNINGTON, INC.",NaN,PO BOX F,NaN,CHARLESTOWN,NH,03603,...,05682,1964-09-22,Inactive - Administratively Terminated,1982-06-30,NaN,6.0,NaN,NaN,NaN,NaN
1542,62004,V13840,Domestic Business Corporation,"BERARDINELLI'S GENERAL STORE, INC.",NaN,MAIN ST RT 104,NaN,FAIRFAX,VT,05454,...,05444,1967-10-24,Inactive - Administratively Terminated,1993-12-31,NaN,12.0,NaN,NaN,NaN,NaN
1867,63049,V15260,Domestic Business Corporation,"HISTORIC CRAFTSBURY GENERAL STORE, INC.",NaN,MAIN ST.,NaN,CRAFTSBURY,VT,05826,...,05826,1969-09-29,Dissolved,1995-09-30,NaN,9.0,NaN,1995-11-08,NaN,NaN
2046,63967,V16003,Domestic Business Corporation,"WAITS RIVER GENERAL STORE, INC.",NaN,NaN,NaN,WAITS RIVER,VT,05086,...,05086,1970-08-25,Dissolved,1983-12-31,NaN,12.0,NaN,1985-05-09,NaN,NaN
2067,64076,V16092,Domestic Business Corporation,"WARDSBORO COUNTRY STORE, INC.",NaN,NaN,NaN,WARDSBORO,VT,05355,...,05355,1970-10-08,Dissolved,1991-12-31,NaN,12.0,NaN,1992-04-14,NaN,NaN
2072,64104,V16115,Domestic Business Corporation,"FRECHETTE'S COUNTRY STORE, INC.",NaN,NaN,NaN,NORTON,VT,05907,...,05855,1970-10-19,Dissolved,1985-12-31,NaN,12.0,NaN,1986-09-30,NaN,NaN
2562,66457,V18089,Domestic Business Corporation,"MIDDLETOWN SPRINGS EAST STREET STORE, INC.",NaN,EAST STREET,NaN,MIDDLETWN SPG,VT,05757,...,05757,1972-08-18,Inactive - Administratively Terminated,1996-12-31,NaN,12.0,NaN,NaN,NaN,NaN
2568,66481,V18108,Domestic Business Corporation,CHELSEA COUNTRY STORE INC,NaN,NaN,NaN,CHELSEA,VT,05038,...,05038,1972-08-28,Dissolved,1988-05-31,NaN,5.0,NaN,1989-06-20,NaN,NaN
2607,66695,V18284,Domestic Business Corporation,"BENSON GENERAL STORE, INC.",NaN,NaN,NaN,BENSON,VT,05731,...,05731,1972-10-25,Inactive - Administratively Terminated,1984-09-30,NaN,9.0,NaN,NaN,NaN,NaN
2619,66758,V18335,Domestic Business Corporation,"BOMOSEEN HARBOR GENERAL STORE, INC.",NaN,"DAVID AVE. N., BX 97",NaN,HYDEVILLE,VT,05750,...,05756,1972-11-08,Inactive - Administratively Terminated,1991-12-31,NaN,12.0,NaN,NaN,NaN,NaN
2643,66907,V18461,Domestic Business Corporation,"WEST BURKE GENERAL STORE, INC.",NaN,NaN,NaN,WEST BURKE,VT,05871,...,05871,1972-12-18,Dissolved,1988-12-31,NaN,12.0,NaN,1989-07-25,NaN,NaN
2656,66954,V18496,Domestic Business Corporation,"FRASERS' GENERAL STORE, INC.",NaN,319 MAIN ST,NaN,NORWICH,VT,05055,...,05055,1972-12-29,Active - In Good Standing,2025-12-31,2026-03-16,12.0,NaN,NaN,NaN,NaN
2668,66994,V18525,Domestic Business Corporation,"MT. HOLLY COUNTRY STORE, INC.",NaN,NaN,NaN,MT. HOLLY,VT,05758,...,05758,1973-01-04,Inactive - Administratively Terminated,1985-12-31,NaN,12.0,NaN,NaN,NaN,NaN
2787,67577,V18991,Domestic Business Corporation,"SOUTH WOODSTOCK COUNTRY STORE, INC.",NaN,RT 106,NaN,SO. WOODSTOCK,VT,05071,...,05091,1973-05-07,Dissolved,2000-12-31,NaN,12.0,NaN,2001-12-28,NaN,NaN
2795,67648,V19054,Domestic Business Corporation,"FAIRFAX VILLAGE STORE, INC.",NaN,NaN,NaN,FAIRFAX,VT,05454,...,05454,1973-05-29,Inactive - Administratively Terminated,1982-12-31,NaN,12.0,NaN,NaN,NaN,NaN
3036,68760,V19937,Domestic Business Corporation,"MILTON GENERAL STORE, INC.",NaN,RAILROAD ST,NaN,MILTON,VT,05468,...,05488,1974-03-29,Inactive - Administratively Terminated,1991-12-31,NaN,12.0,NaN,NaN,NaN,NaN
3054,68822,V19981,Domestic Business Corporation,"SOUTH PEACHAM COUNTRY STORE, INC.",NaN,NaN,NaN,SO. PEACHAM,VT,05862,...,05602,1974-04-09,Dissolved,1982-04-30,NaN,4.0,NaN,1983-09-20,NaN,NaN
3340,70109,V20989,Domestic Business Corporation,"MARSHFIELD GENERAL STORE, INC.",NaN,NaN,NaN,MARSHFIELD,VT,05658,...,05658,1975-04-10,Inactive - Administratively Terminated,1982-12-31,NaN,12.0,NaN,NaN,NaN,NaN
3680,71592,V22137,Domestic Business Corporation,"BEAU'S COUNTRY STORE, INC.",NaN,RT 116,NaN,HINESBURG,VT,05461,...,05461,1976-04-21,Inactive - Administratively Terminated,1982-05-31,NaN,5.0,NaN,NaN,NaN,NaN
3746,71880,V22360,Domestic Business Corporation,"HEATH'S LUDLOW COUNTRY STORE, INC.",NaN,NaN,NaN,LUDLOW,VT,05149,...,05161,1976-06-22,Inactive - Administratively Terminated,1984-12-31,NaN,12.0,NaN,NaN,NaN,NaN
3828,72177,V22576,Domestic Business Corporation,"ROUTE 5 COUNTRY STORE, INC.",NaN,NaN,NaN,W. RIVER JCT.,VT,05001,...,05045,1976-08-24,Inactive - Administratively Terminated,1985-12-31,NaN,12.0,NaN,NaN,NaN,NaN
4322,73967,V23893,Domestic Business Corporation,"COBURNS' GENERAL STORE, INC.",NaN,216 VT RTE 132,NaN,S. STRAFFORD,VT,05070,...,05070,1977-08-22,Active - In Good Standing,2025-12-31,2026-03-16,12.0,NaN,NaN,NaN,NaN
4679,75371,V24718,Domestic Business Corporation,"DRAPER'S GENERAL STORE, INC.",NaN,RT. 100,NaN,LOWELL,VT,05847,...,05847,1978-03-23,Inactive - Administratively Terminated,1983-12-31,NaN,12.0,NaN,NaN,NaN,NaN
4721,75614,V24819,Domestic Business Corporation,G I JOE'S COUNTRY STORE INC,NaN,STAR RT 100,NaN,HANCOCK,VT,05748,...,05748,1978-04-13,Inactive - Administratively Terminated,1982-04-30,NaN,4.0,NaN,NaN,NaN,NaN
4927,76826,V25325,Domestic Business Corporation,"CAVACAS' COUNTRY STORE, LTD.",NaN,NaN,NaN,PROCTOR,VT,05765,...,05765,1978-08-18,Dissolved,1984-07-31,NaN,7.0,NaN,1985-08-15,NaN,NaN
4928,76837,V25329,Domestic Business Corporation,"GRAY'S GENERAL STORE, INC.",NaN,NaN,NaN,DANVILLE,VT,05828,...,05450,1978-08-21,Inactive - Administratively Terminated,1987-08-31,NaN,8.0,NaN,NaN,NaN,NaN
5514,79745,V26609,Domestic Business Corporation,"PEACHAM STORE, INC.",NaN,NaN,NaN,PEACHAM,VT,05862,...,05862,1979-07-10,Dissolved,1988-12-31,NaN,12.0,NaN,1991-08-06,NaN,NaN
5700,80300,V26979,Domestic Business Corporation,"WILLIAMS GENERAL STORE, INC.",NaN,ROUTE 110 MAIN ST.,NaN,TUNBRIDGE,VT,05077,...,05077,1979-10-16,Dissolved,1985-12-31,NaN,12.0,NaN,1987-03-20,NaN,NaN
5765,80495,V27112,Domestic Business Corporation,"FAYSTON COUNTRY STORE, INC.",NaN,NaN,NaN,FAYSTON,VT,05673,...,05602,1979-11-19,Inactive - Administratively Terminated,1983-06-30,NaN,6.0,NaN,NaN,NaN,NaN
5913,80960,V27429,Domestic Business Corporation,"READING COUNTRY STORE, INC.",NaN,NaN,NaN,NaN,NaN,NaN,...,05156,1980-02-04,Inactive - Administratively Terminated,NaN,1981-02-04,2.0,NaN,NaN,NaN,NaN
5976,81161,V27566,Domestic Business Corporation,"STONEY BROOK GENERAL STORE, INC.",NaN,ROUTE 107,NaN,STOCKBRIDGE,VT,05772,...,05482,1980-03-19,Dissolved,1986-03-31,NaN,3.0,NaN,1988-04-12,NaN,NaN
6313,82128,V28201,Domestic Business Corporation,"MCGILL'S GENERAL STORE, INC.",NaN,NaN,NaN,NEWPORT CTR,VT,05857,...,05857,1980-09-12,Inactive - Administratively Terminated,1984-12-31,NaN,12.0,NaN,NaN,NaN,NaN
6900,83552,V29043,Domestic Business Corporation,STOWE BOOK STORE INC.,451211-Book stores,38 Main St.,NaN,STOWE,VT,05672,...,05464,1981-04-27,Active - In Good Standing,2026-03-31,NaN,3.0,NaN,NaN,NaN,NaN
7016,83847,V29222,Domestic Business Corporation,"DICK MAZZA GENERAL STORE, INC.",445110-Supermarkets and Other Grocery (except ...,777 W LAKE SHORE DR.#1,NaN,COLCHESTER,VT,05446,...,05446,1981-06-11,Active - In Good Standing,2026-03-31,NaN,3.0,NaN,NaN,NaN,NaN
7096,84045,V29339,Domestic Business Corporation,"EBENEZER ALLEN COUNTRY STORE AND GIFT SHOP, LTD.",NaN,BURLINGTON SQ. MALL,NaN,BURLINGTON,VT,05401,...,05401,1981-07-08,Inactive - Administratively Terminated,1985-08-31,NaN,8.0,NaN,NaN,NaN,NaN
7251,84415,V29556,Domestic Business Corporation,HARDWICKE'S COUNTRY STORE INC,NaN,HERRICK RD.,NaN,DERBY LINE,VT,05830,...,05676,1981-08-24,Inactive - Administratively Terminated,1992-01-31,NaN,1.0,NaN,NaN,NaN,NaN

In [ ]:
# List of business names to exclude
exclude_names = ['DOLLAR GENERAL STORE', 'COUNTRY STORE PROPERTIES LLC', ]

# Filter out those rows
df_general_stores = df_general_stores[~df_general_stores['BusinessName'].isin(exclude_names)] 
# also need to exclude business names that are other kinds of stores that may include store + city name
df_general_stores = df_general_stores[~df_general_stores['BusinessName'].str.contains(r"\b(BOOK STORE|HARDWARE STORE|THRIFT STORE|GROCERY STORE|SOLAR STORE|FARM STORE|DRUG STORE|ARMY AND NAVY STORE|BRICK STORE|LIQUOR STORE|TOY STORE|BRICK STORE|COLLEGE|DUTY FREE|)\b")]

/var/folders/4t/dlz7f1jn6gl_h8g2l5076hj80000gn/T/ipykernel_38818/1375779940.py:7: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df_general_stores = df_general_stores[~df_general_stores['BusinessName'].str.contains(r"\b(BOOK STORE|HARDWARE STORE|THRIFT STORE|GROCERY STORE|SOLAR STORE|FARM STORE|DRUG STORE|ARMY AND NAVY STORE|BRICK STORE|LIQUOR STORE|TOY STORE|BRICK STORE|COLLEGE)\b")]

In [22]:
# checking to make sure this all worked -- here is the list of stores that dont include "country" or "genera" but are rathe just the town names plus "store"
subset = df_general_stores[
    ~df_general_stores["BusinessName"].str.contains(
        r"\b(country|general)\b",
        case=False,
        na=False
    )]

/var/folders/4t/dlz7f1jn6gl_h8g2l5076hj80000gn/T/ipykernel_38818/78607812.py:3: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  ~df_general_stores["BusinessName"].str.contains(

In [27]:
subset_list = subset['BusinessName'].unique()
for item in subset_list:
    print(item)

GRAFTON VILLAGE STORE, INC.
CHARLESTOWN MILL STORE OF BENNINGTON, INC.
MIDDLETOWN SPRINGS EAST STREET STORE, INC.
FAIRFAX VILLAGE STORE, INC.
PEACHAM STORE, INC.
CASTLETON VILLAGE STORE, INC.
GEORGIA CORNER STORE, INC.
SHELBURNE MILL STORE, INC. THE
TINMOUTH STORE, LTD., THE
NORTH POMFRET STORE, INC., THE
CABOT VILLAGE STORE, INC.
BRADFORD VILLAGE STORE, INC.
WINCHESTER'S STORE, INC.
VILLAGE STORE OF MONKTON, INC.
WESTON VILLAGE STORE, INC.
WOLCOTT STORE, INC.
TOWNSHEND CORNER STORE, INC.
GRAND ISLE STORE, INC. THE
SOUTH LONDONDERRY VILLAGE STORE, INC.
NORTON DUTY FREE STORE, INC.
SIMON'S MILTON STORE, INC.
NEWBURY VILLAGE STORE, INC.
O'BRIEN'S STORE OF WILLISTON, INC.
WEST HARTFORD VILLAGE STORE, INC.
PROCTOR STORE, INC.
SIMON'S WAITSFIELD STORE, INC.
CHITTENDEN STORE & DELI, INC
MARSHFIELD VILLAGE STORE INC
NORTH BENNINGTON VARIETY STORE INC
AR LYNDONVILLE STORE CORP
JRY Burlington Store Corporation
AR SWANTON STORE CORP.
BROOKFIELD VALLEY STORE, LLC
BENSON VILLAGE STORE, LLC
TUNBRIDGE VILLAGE STORE, LLC
WEST HARTFORD VILLAGE STORE, LLC
WOODBURY VILLAGE STORE, LLC
BLOOMFIELD CORNER STORE, LLC
LYNDONVILLE STORE, LLC
RIPTON STORE, LLC
TROY VILLAGE STORE LLC
WASHINGTON VILLAGE STORE LLC.
MANCHESTER VARIETY STORE, LLC
THE NEWFANE STORE LLC
THE DANBY VILLAGE MARKETPLACE AT NICHOLS STORE LLC                 RE LLC        RE
NORTON STORE & DELI LLC
THETFORD VILLAGE STORE LLC
WINOOSKI RIVER STORE, LLC
WHEELOCK VILLAGE STORE LLC
Cabot Store LLC
Leicester convenient store LLC
Simon's North Hero Store, LLC
BURLINGTON SQUARE DEPARTMENT STORE SITE L.P.
BRANDON CASH STORE
VILLAGE STORE OF MIDDLEBURY, THE
NORTH BENNINGTON VARIETY STORE
PLAINFIELD RED STORE
ADDISON FOUR CORNERS' STORE
WEST HARTFORD VILLAGE STORE
SUTTON STORE
SIMON'S WINOOSKI STORE & DELI
MARSHFIELD VILLAGE STORE
STARKSBORO VILLAGE STORE
WEST WARDSBORO STORE, THE
ARLINGTON STORE THE
BENSON VILLAGE STORE
ESSEX ARMY/NAVY STORE
THE BARTON VILLAGE CORNER STORE
BEN FRANKLIN STORE
MILLER'S STORE OF EAST TOPSHAM
GREENSBORO BEND STORE
DANBY FOUR CORNERS STORE
BARTON VILLAGE CORNER STORE THE
SIMON'S ESSEX CENTER STORE & DELI
WINCHESTER'S STORE
FLETCHER'S STORE
DERBY VILLAGE STORE
NEWBURY VILLAGE STORE
WAITSFIELD VILLAGE STORE
CABOT VILLAGE STORE
VILLAGE STORE OF TUNBRIDGE
WHEELOCK VILLAGE STORE
SIMON'S MILTON STORE
THE STORE OF ROCHESTER
HARTFORD CO-OP FOOD STORE
STORE OF ROCHESTER, THE
THE WARREN STORE
ADDISON FOUR CORNERS STORE
NORTH POMFRET STORE
WEST BARNET GEN. STORE
LEWIS STORE, THE
GARDNER'S STORE OF POWNAL
SHIPPING STORE OF MIDDLEBURY
TUNBRIDGE VILLAGE STORE, THE
GRAND ISLE STORE
NORTH POMFRET STORE, THE
UNDERHILL FEED STORE
WOODBURY VILLAGE STORE, THE
HOOGIE'S CRAFTSBURY VILLAGE STORE
WOODBURYS THE BUILDING STORE
EAST DUMMERSTON COMMUNITY STORE
JERICHO BEVERAGE STORE
WOODBURY VILLAGE STORE  THE
NAPA AND BORDEAUX WINES AT THE WARREN STORE
WOLCOTT STORE AND GARAGE
WINOOSKI HALAL STORE
ELMORE STORE, THE
THE TUNBRIDGE STORE
HOME STORE OF MANCHESTER  THE
HOME STORE OF STRATTON  THE
BOLTON STORE (THE)
WEST CHARLESTON CORNER STORE
MANCHESTER MUSIC STORE
BRADFORD VILLAGE STORE
TOWNSHEND CORNER STORE (THE)
THE LITTLE STORE AT CLARENDON SPRINGS
TINMOUTH STORE (THE)
VILLAGE STORE OF SHELBURNE, THE
MUGUIRA'S HILL SIDE STORE
CRAFTSBURY CORNER STORE
VERGENNES DISCOUNT STORE
SIMON'S BERLIN STORE
LOWELL'S CORNER STORE
SIMON'S MONTPELIER STORE & DELI
WEST WARDSBORO STORE
SOUTH RYEGATE VILLAGE STORE
THETFORD CENTER VILLAGE STORE
PITTSFORD VILLAGE STORE
WOLFFE'S PITTSFORD VILLAGE STORE
TOWNSHEND CORNER STORE, THE
BOLTON STORE
MORRISTOWN CORNER STORE, THE
BROOKFIELD VALLEY STORE
BARNET VILLAGE STORE
MANCHESTER WOOD FACTORY STORE
TOWNSHEND CORNER STORE
TUNBRIDGE VILLAGE STORE
FAYSTON STORE PARTNERS
MIRANDA THOMAS CHARLES SHACKLETON WORKSHOP STORE, THE
CABOT CREAMERY QUECHEE STORE
EAST BROOKFIELD DELI/STORE
CASTLETON CORNERS CONVENIENCE STORE
SHOREHAM CORNER STORE
DERBY ROAD OUTLET STORE
DORSET UNION STORE
BRANDON VARIETY STORE
BARTON VILLAGE CORNER STORE, THE
MORRISTOWN CORNER STORE
RICHFORD CONVENIENT STORE
NAME BRAND STORE OF STOWE
THE ELMORE STORE
MANCHESTER VARIETY STORE
SIMON'S SHELBURNE ROAD STORE
WOODBURY VILLAGE STORE
STORE OF ROCHESTER THE
NEWBURY VILLAGE STORE AND THISTLE CAFE
BRISTOL C STORE
WASHINGTON VILLAGE STORE
THE NEWFANE STORE
Grafton Village Cheese Store
Cabot Village Store
HARDWICK Gas & Convenience Store
SHREWSBURY COOPERATIVE AT PIERCE'S STORE
CHELSEA COMMUNITY STORE, INC.
Orwell Store Community Trust, Inc.

In [28]:
df_general_stores.to_csv('data/cleaned/general_stores_sorted_from_excelsheets.csv', index=False)